"""Operational-claim regressions added during the v0.7 referee audit."""
from pathlib import Path
import sys
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from qrb.graph_response import three_separable_elliptope_matrix
from qrb.input_output import THREE_SETTINGS, sign_measurement_matrix

# The advertised three phase-coded settings must reconstruct all pair responses.
M = sign_measurement_matrix(THREE_SETTINGS)
assert abs(np.linalg.det(M)) > 1e-12
Minv = np.linalg.inv(M)
for r in [
    np.array([0.12, -0.21, 0.07]),
    np.array([0.5, 0.5, 0.5]),
    np.array([2/3, 2/3, 2/3]),
]:
    x = M @ r
    assert np.allclose(Minv @ x, r, atol=1e-13)

# Random fixed-marginal separable responses generated by equatorial product
# states obey the exact elliptope compatibility condition.
rng = np.random.default_rng(20260827)
for _ in range(1000):
    phi = rng.uniform(-np.pi, np.pi, size=3)
    r = np.array([
        0.5*np.cos(phi[0]-phi[1]),
        0.5*np.cos(phi[0]-phi[2]),
        0.5*np.cos(phi[1]-phi[2]),
    ])
    G = three_separable_elliptope_matrix(*r)
    assert np.linalg.eigvalsh(G).min() > -2e-12

# The W/anti-W fixed-marginal response lies strictly outside the separable body.
rw = np.array([2/3, 2/3, 2/3])
Gw = three_separable_elliptope_matrix(*rw)
assert np.linalg.eigvalsh(Gw).min() < -0.3

print('v0.7 operational-claim tests passed')
